version: "3.7"
services:
  app:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - php

  php:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"

volumes:
  postgres-volume:

